name       : tidy-html5
version    : 5.2.0
release    : 1
source     :
    - https://github.com/htacg/tidy-html5/archive/5.2.0.tar.gz : 80533415acf11ac55f24b874ab39448e390ffec3c2b93df4b857d15602fc7c4d
license    : Zlib
component  : programming.tools
summary    : tidy-html5 corrects and cleans up HTML and XML documents by fixing markup errors and upgrading legacy code to modern standards.
description: |
    tidy-html5 corrects and cleans up HTML and XML documents by fixing markup errors and upgrading legacy code to modern standards.
builddeps  :
    - pkgconfig(libxslt)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/lib/*.a
