name       : tidy-html5
version    : 5.8.0
release    : 4
source     :
    - https://github.com/htacg/tidy-html5/archive/5.8.0.tar.gz : 59c86d5b2e452f63c5cdb29c866a12a4c55b1741d7025cf2f3ce0cde99b0660e
license    : Zlib
component  : programming.tools
summary    : tidy-html5 corrects and cleans up HTML and XML documents by fixing markup errors and upgrading legacy code to modern standards.
description: |
    tidy-html5 corrects and cleans up HTML and XML documents by fixing markup errors and upgrading legacy code to modern standards.
builddeps  :
    - pkgconfig(libxslt)
setup      : |
    %cmake_ninja .
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm $installdir/usr/lib/*.a
